version: '3.8'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_DB}
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
